
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 57
#define YY_END_OF_BUFFER 58
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[333] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    7,    7,    0,    0,
        0,    0,   58,   56,   55,   56,   56,   13,   13,   54,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   43,   41,   42,   56,   28,   26,   27,
       56,   47,   45,   46,   56,   19,   56,   18,   56,   23,
       56,   22,   51,   50,   53,   50,   50,   52,   37,   56,
       35,   35,   35,   56,   11,   10,    9,   12,   56,   32,
       31,   30,   33,   56,   56,    7,   56,    6,    4,    4,

       55,    0,    1,    2,   13,   13,    0,   13,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   43,   42,   43,   41,   42,    0,
       28,   27,   28,   27,    0,   47,   46,   47,   46,    0,
       19,   18,   19,   17,   18,    0,   23,   22,   23,   21,
       22,   50,    0,    0,   35,   35,    0,   11,   12,   11,
        9,   12,    0,   32,   33,   32,   30,   33,    0,    0,
        7,    0,    6,    3,    0,   13,   49,   49,   49,    0,
        0,    0,    0,   38,    0,    0,    0,    0,    0,    0,
        0,   35,    0,   36,   14,    0,    8,    0,   13,   49,

       49,    0,    0,    0,   38,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   13,    0,    0,    0,    0,    0,
        0,    0,   34,    0,    0,    0,    0,   13,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   13,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       13,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    5,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   16,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   44,    0,    0,    0,   25,
        0,    0,    0,    0,    0,    0,    0,   39,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   29,    0,    0,    0,    0,    0,    0,    0,    0,
       40,    0,   48,    0,   20,    0,   15,   48,    0,    0,
       24,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    4,    5,    1,    6,
        7,    8,    1,    9,   10,    1,   11,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,   14,    1,
       15,   16,    1,    1,   17,   18,   18,   18,   18,   19,
       20,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
        1,    1,    1,    1,   21,    1,   22,   23,   24,   24,

       25,   26,   24,   27,   28,   24,   24,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   24,   24,
       40,   24,   41,   42,   43,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[44] =
    {   0,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    1,    1,    1,    5,    5,    5,    5,
        6,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        1,    1,    1
    } ;

static const flex_int16_t yy_base[342] =
    {   0,
        0,    0,   43,    0,   80,  113,  151,    0,  194,    0,
      237,    0,   87,   89,   91,  108,  280,    0,  323,    0,
      366,    0,  409,    0,   94,   96,  452,    0,    0,    0,
     1001, 1000, 1007, 1010,  124, 1003,  997,  135,  142, 1010,
      999,  170,   83,   92,   94,  126,  974,  974,  970,  988,
      962,  976,  494,  154,  985,  156,  496,  159, 1010,  164,
      498,  174, 1010,  176,  511,  181,  984,  183,  513,  185,
      983,  187, 1010, 1010, 1010,  982, 1010, 1010, 1010,  516,
        0,  521,  526,  531,  189, 1010,  540,  544,  546,  548,
     1010,  550,  555,  980,  964,  559,  978,    0, 1010,  979,

      561,  986, 1010, 1010,  563,  565,  975,  567,  564,  569,
      971,  583,  953,  948,  956,  589,  594,  942,  940,  939,
      597,  919,  905,  602,  610,  612,  615,  926,  617,  619,
      621,  623,  627,  629,  632,  634,  636,  640,  645,  647,
      649,  651,  655,  924,  657,  662,  664,  666,  670,  923,
      675,  922,  677,  917,    0,  679,  683,  681,  686,  692,
      696,  698,  700,  704,  708,  710,  713,  715,  916,  899,
      717,  914,    0, 1010,  913,  719, 1010,  915,  721,  898,
      887,  888,  725,  727,  895,  899,  882,  731,  902,  880,
      888, 1010,  734, 1010, 1010,  887, 1010,  742,  747,  902,

      749,  887,  872,  852,  751,  863,  848,  845,  753,  844,
      842,  820,  755,  817,  761,  827,  807,  816,  799,  799,
      796,  764, 1010,  768,  779,  772,  768,  769,  763,  753,
      737,  743,  729,  732,  774,  717,  725,  710,  776,  701,
      707,  691,  688,  671,  683,  778,  683,  649,  632,  633,
      783,  790,  624,  614,  792,  618,  591,  797,  804,  573,
      584,  806,  808,  588,  576,  571,  810,  577,  550,  540,
      812, 1010,  814,  543,  538,  822,  530,  512,  824,  510,
      510,  826,  500,  828,  830, 1010,  485,  488,  833, 1010,
      475,  472,  838,  841,  493,  482,  843, 1010,  845,  853,

      857,  477,  178,  144,  859,  161,  865,  150,  873,  137,
      877, 1010,  114,  879,  881,  885,  889,  130,  105,  891,
     1010,  893,  121,  901, 1010,  903, 1010,  106,  905,   92,
       83, 1010,  942,  948,  954,  959,  963,  967,  971,  975,
      979
    } ;

static const flex_int16_t yy_def[342] =
    {   0,
      332,    1,  332,    3,  333,  333,  333,    7,  332,    9,
      332,   11,  333,  333,  333,  333,  332,   17,  332,   19,
      332,   21,  332,   23,  333,  333,  332,   27,  333,  333,
      334,  334,  332,  332,  332,  335,  332,  336,  336,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      337,  337,  337,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  338,  332,  332,

      332,  335,  332,  332,  332,  336,  332,  336,  339,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  337,  337,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  338,  332,  332,  336,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  336,  332,

      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  336,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  336,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  336,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      336,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  340,  332,  332,  332,  332,  332,  332,  332,
      332,  341,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  341,  332,  332,  332,  332,  332,  332,

      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,    0,  332,  332,  332,  332,  332,  332,  332,  332,
      332
    } ;

static const flex_int16_t yy_nxt[1054] =
    {   0,
       34,   35,   35,   36,   34,   34,   34,   34,   34,   34,
       37,   34,   34,   34,   34,   34,   38,   38,   38,   38,
       34,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   39,   38,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   40,
       34,   34,   34,   34,   41,   34,   34,   34,   34,   42,
       42,   42,   42,   34,   43,   41,   41,   41,   41,   41,
       41,   41,   41,   44,   41,   41,   41,   41,   45,   41,
       41,   41,   41,   34,   34,   34,   46,  109,   65,   65,
       65,   65,   69,   69,  331,   66,  109,   66,  109,   70,

       66,   47,   66,  331,   70,   48,   94,   49,   94,   69,
       69,  113,   95,   50,   95,   51,   70,  328,   52,   46,
       67,   70,   67,  114,   71,  101,  101,  116,  116,   68,
      115,   68,  328,   72,   47,  327,  105,  105,   48,  117,
       49,   71,  326,  105,  105,  319,   50,  107,   51,  316,
       72,   52,   53,   53,  107,  127,  127,  129,  129,   54,
      133,  133,  315,  108,   54,  134,  134,   55,   55,   55,
       55,  110,  110,  314,  109,  138,  138,  139,  139,  111,
      313,  112,  143,  143,  145,  145,  149,  149,  151,  151,
      160,  160,  312,   56,   34,   57,   57,   34,   34,   34,

       34,   34,   58,   34,   34,   59,   34,   58,   34,   34,
       34,   34,   34,   34,   34,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   34,   34,   60,   34,   61,   61,
       34,   34,   34,   34,   34,   62,   34,   34,   63,   34,
       62,   34,   34,   34,   34,   34,   34,   34,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   34,   34,   64,
       34,   34,   34,   34,   73,   34,   34,   34,   34,   34,
       34,   74,   34,   75,   34,   34,   76,   76,   76,   76,

       34,   74,   74,   74,   77,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       34,   78,   34,   34,   34,   34,   34,   34,   34,   79,
       34,   34,   34,   34,   80,   34,   34,   34,   34,   81,
       81,   81,   81,   34,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   83,   82,   82,   82,
       82,   82,   82,   34,   34,   34,   34,   84,   84,   34,
       34,   34,   34,   34,   85,   34,   34,   86,   34,   85,
       34,   34,   34,   34,   34,   34,   34,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,

       86,   86,   86,   86,   86,   86,   87,   34,   88,   34,
       89,   89,   34,   34,   34,   34,   34,   90,   34,   34,
       91,   34,   90,   34,   34,   34,   34,   34,   34,   34,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   92,
       34,   93,   34,   96,   96,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   97,   34,   34,   34,   98,   98,
       98,   98,   34,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   34,   34,   34,  124,  124,  130,  130,  135,

      135,  311,  125,  304,  131,  303,  136,  125,  302,  131,
      301,  136,  140,  140,  146,  146,  300,  153,  153,  141,
      299,  147,  153,  153,  141,  154,  147,  153,  153,  296,
      154,  292,  157,  157,  291,  154,  126,  156,  132,  158,
      137,  161,  161,  288,  158,  162,  162,  163,  163,  166,
      166,  167,  167,  142,  164,  148,  168,  168,  287,  164,
      171,  171,  101,  101,  105,  105,  105,  105,  105,  105,
      110,  110,  284,  159,  283,  107,  281,  107,  111,  107,
      178,  178,  178,  178,  110,  110,  280,  109,  165,  279,
      116,  116,  111,  278,  112,  183,  183,  277,  188,  188,

      276,  176,  117,  124,  124,  275,  189,  184,  121,  274,
      125,  127,  127,  129,  129,  125,  127,  127,  129,  129,
      130,  130,  133,  133,  134,  134,  270,  131,  133,  133,
      134,  134,  131,  135,  135,  138,  138,  139,  139,  269,
      136,  138,  138,  266,  126,  136,  139,  139,  140,  140,
      143,  143,  145,  145,  265,  141,  143,  143,  145,  145,
      141,  132,  261,  146,  146,  149,  149,  151,  151,  260,
      147,  149,  149,  259,  137,  147,  151,  151,  153,  153,
      193,  193,  160,  160,  157,  157,  154,  162,  162,  142,
      156,  158,  194,  160,  160,  258,  158,  161,  161,  162,

      162,  163,  163,  257,  148,  166,  166,  256,  164,  168,
      168,  166,  166,  164,  167,  167,  168,  168,  171,  171,
      105,  105,  201,  201,  255,  159,  183,  183,  205,  205,
      254,  107,  188,  188,  253,  193,  193,  252,  184,  250,
      189,  249,  165,  213,  213,  248,  199,  194,  105,  105,
      201,  201,  205,  205,  222,  222,  213,  213,  223,  107,
      245,  214,  105,  105,  244,  222,  222,  243,  215,  223,
      105,  105,  242,  107,  214,  246,  246,  105,  105,  246,
      246,  107,  241,  228,  262,  262,  247,  240,  107,  238,
      247,  263,  263,  267,  267,  107,  237,  239,  271,  271,

      251,  236,  264,  235,  268,  273,  273,  262,  262,  263,
      263,  267,  267,  271,  271,  273,  273,  234,  107,  233,
      264,  232,  268,  285,  285,  289,  289,  293,  293,  297,
      297,  285,  285,  298,  289,  289,  231,  272,  295,  293,
      293,  230,  293,  293,  297,  297,  305,  305,  298,  229,
      295,  227,  272,  295,  307,  307,  226,  306,  309,  309,
      305,  305,  286,  225,  290,  308,  307,  307,  224,  310,
      286,  306,  221,  290,  309,  309,  220,  308,  317,  317,
      320,  320,  322,  322,  219,  310,  324,  324,  218,  318,
      317,  317,  320,  320,  322,  322,  217,  323,  323,  323,

      323,  318,  324,  324,  329,  329,  329,  329,  216,  323,
      323,  323,  323,  200,  212,  211,  210,  209,  208,  321,
      207,  206,  204,  203,  202,  325,  200,  198,  197,  196,
      195,  321,  192,  152,  150,  144,  330,  128,  330,  191,
      190,  325,   34,   34,   34,   34,   34,   34,   99,   99,
       99,   99,   99,   99,  102,  102,  102,  102,  102,  102,
      106,  106,  106,  106,  106,  155,  187,  155,  155,  173,
      186,  173,  173,  177,  185,  177,  282,  182,  181,  282,
      294,  294,  294,  294,  294,  180,  179,  175,  103,  174,
      172,  170,  169,  152,  150,  144,  128,  123,  122,  121,

      120,  119,  118,  109,  104,  103,  332,  100,  100,   33,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332
    } ;

static const flex_int16_t yy_chk[1054] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    5,   43,   13,   13,
       14,   14,   15,   15,  331,   13,   44,   14,   45,   15,

       13,    5,   14,  330,   15,    5,   25,    5,   26,   16,
       16,   43,   25,    5,   26,    5,   16,  328,    5,    6,
       13,   16,   14,   44,   15,   35,   35,   46,   46,   13,
       45,   14,  323,   15,    6,  319,   38,   38,    6,   46,
        6,   16,  318,   39,   39,  313,    6,   38,    6,  310,
       16,    6,    7,    7,   39,   54,   54,   56,   56,    7,
       58,   58,  308,   39,    7,   60,   60,    7,    7,    7,
        7,   42,   42,  306,   42,   62,   62,   64,   64,   42,
      304,   42,   66,   66,   68,   68,   70,   70,   72,   72,
       85,   85,  303,    7,    9,    9,    9,    9,    9,    9,

        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,

       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,

       21,   21,   21,   21,   21,   21,   21,   21,   21,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   53,   53,   57,   57,   61,

       61,  302,   53,  296,   57,  295,   61,   53,  292,   57,
      291,   61,   65,   65,   69,   69,  288,   80,   80,   65,
      287,   69,   82,   82,   65,   80,   69,   83,   83,  283,
       82,  281,   84,   84,  280,   83,   53,   83,   57,   84,
       61,   87,   87,  278,   84,   88,   88,   89,   89,   90,
       90,   92,   92,   65,   89,   69,   93,   93,  277,   89,
       96,   96,  101,  101,  105,  105,  106,  106,  108,  108,
      110,  110,  275,   84,  274,  105,  270,  106,  110,  108,
      109,  109,  109,  109,  112,  112,  269,  112,   89,  268,
      116,  116,  112,  266,  112,  117,  117,  265,  121,  121,

      264,  108,  116,  124,  124,  261,  121,  117,  121,  260,
      124,  125,  125,  126,  126,  124,  127,  127,  129,  129,
      130,  130,  131,  131,  132,  132,  257,  130,  133,  133,
      134,  134,  130,  135,  135,  136,  136,  137,  137,  256,
      135,  138,  138,  254,  124,  135,  139,  139,  140,  140,
      141,  141,  142,  142,  253,  140,  143,  143,  145,  145,
      140,  130,  250,  146,  146,  147,  147,  148,  148,  249,
      146,  149,  149,  248,  135,  146,  151,  151,  153,  153,
      156,  156,  158,  158,  157,  157,  153,  159,  159,  140,
      156,  157,  156,  160,  160,  247,  157,  161,  161,  162,

      162,  163,  163,  245,  146,  164,  164,  244,  163,  165,
      165,  166,  166,  163,  167,  167,  168,  168,  171,  171,
      176,  176,  179,  179,  243,  157,  183,  183,  184,  184,
      242,  176,  188,  188,  241,  193,  193,  240,  183,  238,
      188,  237,  163,  198,  198,  236,  176,  193,  199,  199,
      201,  201,  205,  205,  209,  209,  213,  213,  209,  199,
      234,  198,  215,  215,  233,  222,  222,  232,  199,  222,
      228,  228,  231,  215,  213,  235,  235,  239,  239,  246,
      246,  228,  230,  215,  251,  251,  235,  229,  239,  227,
      246,  252,  252,  255,  255,  251,  226,  228,  258,  258,

      239,  225,  252,  224,  255,  259,  259,  262,  262,  263,
      263,  267,  267,  271,  271,  273,  273,  221,  262,  220,
      263,  219,  267,  276,  276,  279,  279,  282,  282,  284,
      284,  285,  285,  284,  289,  289,  218,  258,  282,  293,
      293,  217,  294,  294,  297,  297,  299,  299,  297,  216,
      293,  214,  271,  294,  300,  300,  212,  299,  301,  301,
      305,  305,  276,  211,  279,  300,  307,  307,  210,  301,
      285,  305,  208,  289,  309,  309,  207,  307,  311,  311,
      314,  314,  315,  315,  206,  309,  316,  316,  204,  311,
      317,  317,  320,  320,  322,  322,  203,  315,  315,  315,

      315,  317,  324,  324,  326,  326,  329,  329,  202,  322,
      322,  322,  322,  200,  196,  191,  190,  189,  187,  314,
      186,  185,  182,  181,  180,  316,  178,  175,  172,  170,
      169,  320,  154,  152,  150,  144,  326,  128,  329,  123,
      122,  324,  333,  333,  333,  333,  333,  333,  334,  334,
      334,  334,  334,  334,  335,  335,  335,  335,  335,  335,
      336,  336,  336,  336,  336,  337,  120,  337,  337,  338,
      119,  338,  338,  339,  118,  339,  340,  115,  114,  340,
      341,  341,  341,  341,  341,  113,  111,  107,  102,  100,
       97,   95,   94,   76,   71,   67,   55,   52,   51,   50,

       49,   48,   47,   41,   37,   36,   33,   32,   31,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "grammar.l"
#line 2 "grammar.l"
    /* Scirtocea Bianca 331CB */
#include <string>
#include <vector>
#include <set>
#include <map>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
using namespace std;

/* Structuri de date principale */

// Defineste o tranziție în automatul finit
struct Transition {
    string fromState;
    string symbol;   
    string toState;  
};

// Defineste structura unui automat finit complet
struct FiniteAutomaton {
    string name;                 
    set<string> alphabet;       
    set<string> states;         
    set<string> finalStates;    
    string initialState;        
    vector<Transition> transitions; 
};

// Defineste o producție în gramatică
struct Production {
    string left;    // partea stângă (non-terminal)
    string right;   // partea dreaptă (secvență de simboluri)
};

// Defineste structura unei gramatici complete
struct Grammar {
    string name;                         
    set<string> nonterminals;           
    set<string> alphabet;               
    string startSymbol;                 
    vector<pair<string, vector<string>>> productions; 
};

// Defineste o variabilă cu domeniu
struct Variable {
    string name;          
    set<string> domain;   
    bool isLocal;         
};

// Flag pentru prima gramatică procesată (formatare output)
static bool firstGrammar = true;         

// Variabile pentru procesarea producțiilor
string currentLeftSide;                  
string currentRightSide;                 

// Pointeri la structurile curente în procesare
Grammar* currentGrammar = nullptr;       
FiniteAutomaton* currentAutomaton = nullptr; 
Variable* currentVariable = nullptr;     
vector<Variable> globalVariables;        

// Flag-uri pentru contextul curent de procesare
bool insideGrammar = false;
bool insideAutomaton = false;

// Variabile temporare pentru procesarea tranzițiilor
string currentState;
string currentSymbol;

/* Declaratii anticipate ale funcțiilor principale */
void printGrammarInfo();
string determineGrammarType(const Grammar& g);
bool isDeterministic(const FiniteAutomaton& fa);
void printAutomatonInfo();
bool isLocalVariable(const string& symbol);

/* Configurare Flex */
#line 870 "lex.yy.c"
#define YY_NO_INPUT 1

#line 873 "lex.yy.c"

#define INITIAL 0
#define IN_GRAMMAR 1
#define IN_AUTOMATON 2
#define IN_NONTERMINALS 3
#define IN_ALPHABET_AUTOMATON 4
#define IN_ALPHABET_GRAMMAR 5
#define IN_STATES 6
#define IN_FINAL_STATES 7
#define IN_PRODUCTION 8
#define IN_TRANSITION 9
#define IN_VARIABLE_DOMAIN 10
#define IN_VARIABLE_LOCAL 11
#define READ_AUTOMATON_NAME 12
#define READ_VARIABLE_NAME 13
#define READ_GRAMMAR_NAME 14
#define COMMENT 15

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 112 "grammar.l"


#line 115 "grammar.l"
    /* Reguli pentru procesarea comentariilor în cod */
#line 1108 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 333 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1010 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 116 "grammar.l"
/* Ignoră comentariile care încep cu % până la sfârșitul liniei */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 117 "grammar.l"
{ BEGIN(COMMENT); }  /* Începe procesarea comentariului multi-line */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 118 "grammar.l"
{ BEGIN(INITIAL); } /* Termină procesarea comentariului multi-line */
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 119 "grammar.l"
/* Ignoră orice caracter din interiorul comentariului */
	YY_BREAK
/* Definire variabila - formatul ::= {domain} */
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 122 "grammar.l"
{ 
    BEGIN(READ_VARIABLE_NAME); 
}
	YY_BREAK
/* Citeste numele variabilei pana la ::= */
case 6:
YY_RULE_SETUP
#line 127 "grammar.l"
{
    currentVariable = new Variable();
    currentVariable->name = yytext;
    BEGIN(IN_VARIABLE_DOMAIN);
}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 133 "grammar.l"
/* ignora whitespace */
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 134 "grammar.l"
{ BEGIN(IN_VARIABLE_DOMAIN); }
	YY_BREAK
/* Domeniu variabilă - Formatul: {val1, val2, ..., valn} */
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 137 "grammar.l"
/* Ignora acolada si whitespace */
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 138 "grammar.l"
{
    if(currentVariable) currentVariable->domain.insert(yytext);
}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 141 "grammar.l"
/* Ignora separatorii si whitespace-ul asociat */
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 142 "grammar.l"
{
    /* Afișează informații despre variabila globală dacă nu suntem în contextul unei gramatici */
    if(currentVariable) {
        if(!insideGrammar) {
            cout << endl;
            cout << "Variabila globala:" << endl;
            cout << "    Identificator: " << currentVariable->name << endl;
            cout << "    Domeniu: {";
            bool first = true;
            for(const auto& elem : currentVariable->domain) {
                if(!first) cout << ", ";
                cout << elem;
                first = false;
            }
            cout << "}" << endl;  
        }
        delete currentVariable;
        currentVariable = nullptr;
    }
    BEGIN(INITIAL);
}
	YY_BREAK
/* Definire automat - Formatul: identifier ::= FiniteAutomaton(...) */
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 165 "grammar.l"
{ 
    currentAutomaton = new FiniteAutomaton();
    currentAutomaton->name = yytext;
    BEGIN(READ_AUTOMATON_NAME);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 171 "grammar.l"
{ /* continuă procesarea */ }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 172 "grammar.l"
{ BEGIN(IN_AUTOMATON); }
	YY_BREAK
/* Stari - Formatul: states :: {q0, q1, ..., qn} */
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 175 "grammar.l"
{ BEGIN(IN_STATES); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 176 "grammar.l"
{ currentAutomaton->states.insert(yytext); }
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 177 "grammar.l"
{ BEGIN(IN_AUTOMATON); }
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 178 "grammar.l"
/* Procesează separatorii dintre stări */
	YY_BREAK
/* Stari finale - Formatul: final_states :: {q1, q2, ..., qn} */
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 181 "grammar.l"
{ BEGIN(IN_FINAL_STATES); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 182 "grammar.l"
{ currentAutomaton->finalStates.insert(yytext); }
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 183 "grammar.l"
{ BEGIN(IN_AUTOMATON); }
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 184 "grammar.l"
/* Procesează separatorii */
	YY_BREAK
/* Stare initiala - Formatul: initial_state :: q0 */
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 187 "grammar.l"
{
    string temp = yytext;
    size_t pos = temp.find("::");
    currentAutomaton->initialState = temp.substr(pos + 2);
}
	YY_BREAK
/* Alfabet pentru automat */
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 194 "grammar.l"
{ BEGIN(IN_ALPHABET_AUTOMATON); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 195 "grammar.l"
{ 
    if(currentAutomaton) {
        currentAutomaton->alphabet.insert(yytext);
    }
}
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 200 "grammar.l"
{ BEGIN(IN_AUTOMATON); }
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 201 "grammar.l"
/* Proceseaza separtorii */
	YY_BREAK
/* Variabilelor locale pentru automat */
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 204 "grammar.l"
{
    currentVariable = new Variable();
    string temp = yytext;

    // Salt peste cuvantul variable
    size_t start = temp.find_first_not_of(" \t\n\r", 8);
    size_t end = temp.find("::=");
    currentVariable->name = temp.substr(start, end-start);
    
    currentVariable->isLocal = true;  // Marchează ca variabilă locală
    BEGIN(IN_VARIABLE_LOCAL);
}
	YY_BREAK
/* Procesarea domeniului variabilelor locale */
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 218 "grammar.l"
/* Procesează începutul domeniului */
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 220 "grammar.l"
{
    if(currentVariable) currentVariable->domain.insert(yytext);
}
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 223 "grammar.l"
/* Procesează separatorii */
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 224 "grammar.l"
{
    BEGIN(IN_AUTOMATON);  
}
	YY_BREAK
/* Tranzitii automat - Format: stare_curenta -> (simbol -> stare_destinatie) */
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 229 "grammar.l"
{
    currentState = yytext;
    size_t arrowPos = currentState.find("->");
    currentState = currentState.substr(0, arrowPos);
    while(isspace(currentState.back()))
        currentState.pop_back();
    BEGIN(IN_TRANSITION);
}
	YY_BREAK
/* Procesarea simbolului de tranziție */
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 238 "grammar.l"
{
    string symbol = yytext;
    size_t arrowPos = symbol.find("->");
    symbol = symbol.substr(0, arrowPos);
    while(isspace(symbol.back()))
        symbol.pop_back();
    
    if(isLocalVariable(symbol)) {
        currentSymbol = "*VARIABLE*";
    } else {
        currentSymbol = symbol;
        currentAutomaton->alphabet.insert(symbol);
    }
}
	YY_BREAK
/* Procesarea stării destinație în tranziții */
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 254 "grammar.l"
{
    string targetState = yytext;
    targetState.pop_back(); // Elimină caracterul ';'
    while(isspace(targetState.back()))
        targetState.pop_back();
    
    /* Cazul special când simbolul este o variabilă:
     * Expandăm variabila în toate valorile din domeniul ei
     * și creăm câte o tranziție pentru fiecare valoare
     */
    if(currentSymbol == "*VARIABLE*" && currentVariable) {
        for(const auto& sym : currentVariable->domain) {
            Transition t;
            t.fromState = currentState;
            t.symbol = sym;
            t.toState = targetState;
            currentAutomaton->transitions.push_back(t);
            currentAutomaton->alphabet.insert(sym);
        }
    } else {
        /* Cazul normal: o singură tranziție cu simbolul dat */
        Transition t;
        t.fromState = currentState;
        t.symbol = currentSymbol;
        t.toState = targetState;
        currentAutomaton->transitions.push_back(t);
    }
}
	YY_BREAK
/* Finalizarea unei tranziții */
case 37:
YY_RULE_SETUP
#line 284 "grammar.l"
{
    BEGIN(IN_AUTOMATON);
}
	YY_BREAK
/* Finalizarea definiției automatului */
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 289 "grammar.l"
{
    if(currentAutomaton) {
        printAutomatonInfo();
        delete currentAutomaton;
        currentAutomaton = nullptr;
    }
    // Resetam variabila curenta dupa printare
    if(currentVariable) {
        delete currentVariable;
        currentVariable = nullptr;
    }
    insideAutomaton = false;
    BEGIN(INITIAL);
}
	YY_BREAK
/* Definire gramatică - Format: identifier ::= Grammar(...) */
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 305 "grammar.l"
{
    if(currentGrammar != nullptr) 
        delete currentGrammar;
    
    currentGrammar = new Grammar();
    currentGrammar->name = yytext;
    size_t endPos = currentGrammar->name.find("::=");
    currentGrammar->name = currentGrammar->name.substr(0, endPos);

    while(isspace(currentGrammar->name.back()))
        currentGrammar->name.pop_back();

    insideGrammar = true;
    BEGIN(IN_GRAMMAR);
}
	YY_BREAK
/* Neterminale */
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 322 "grammar.l"
{ BEGIN(IN_NONTERMINALS); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 323 "grammar.l"
{ currentGrammar->nonterminals.insert(yytext); }
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 324 "grammar.l"
{ BEGIN(IN_GRAMMAR); }
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 325 "grammar.l"
/* Ignoră separatorii și whitespace-ul asociat */
	YY_BREAK
/* Alfabet gramatica*/
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 328 "grammar.l"
{ BEGIN(IN_ALPHABET_GRAMMAR); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 329 "grammar.l"
{ currentGrammar->alphabet.insert(yytext); }
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 330 "grammar.l"
{ BEGIN(IN_GRAMMAR); }
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 331 "grammar.l"
/* Ignoră separatorii și whitespace-ul asociat */
	YY_BREAK
/* Simbol start gramatica */
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 334 "grammar.l"
{
    string temp = yytext;
    size_t pos = temp.find("::");
    currentGrammar->startSymbol = temp.substr(pos + 2);
}
	YY_BREAK
/* Producții gramatica partea stanga */
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 341 "grammar.l"
{
    currentLeftSide = string(yytext);
    // Dacă conține "->", păstrăm doar partea din stânga
    size_t arrowPos = currentLeftSide.find("->");

    // Daca gasim sageata
    if (arrowPos != string::npos) {
        currentLeftSide = currentLeftSide.substr(0, arrowPos);
        while(isspace(currentLeftSide.back()))
            currentLeftSide.pop_back();
    }
    currentRightSide = "";
    BEGIN(IN_PRODUCTION);
}
	YY_BREAK
/* Procesarea părții drepte a unei producții - Formatul: simbol simbol ... | simbol simbol ... | ... */
case 50:
YY_RULE_SETUP
#line 357 "grammar.l"
{
    /* Adaugă & ca separator între simboluri, doar dacă nu e primul simbol */
    if(!currentRightSide.empty()) 
        currentRightSide += "&";
    currentRightSide += yytext;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 364 "grammar.l"
/* Ignoră & pentru că îl adăugăm automat mai sus */
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 366 "grammar.l"
{
    /* Convertește partea dreaptă într-un vector de string-uri */
    vector<string> rightParts;
    size_t pos = 0;
    string rightSide = currentRightSide;

    /* Separă string-ul la & și adaugă fiecare parte în vector */
    while ((pos = rightSide.find("&")) != string::npos) {
        rightParts.push_back(rightSide.substr(0, pos));
        rightSide.erase(0, pos + 1);
    }

    /* Adaugă și ultima parte dacă există */
    if (!rightSide.empty()) {
        rightParts.push_back(rightSide);
    }

    /* Adaugă producția în gramatică și resetează buffer-ul */
    currentGrammar->productions.push_back({currentLeftSide, rightParts});
    currentRightSide = "";
}
	YY_BREAK
/* Procesează ; care marchează sfârșitul unei producții complete */
case 53:
YY_RULE_SETUP
#line 389 "grammar.l"
{
    // Verifică dacă există conținut în currentRightSide înainte de a procesa
    if (!currentRightSide.empty()) {
        vector<string> rightParts;
        size_t pos = 0;
        string rightSide = currentRightSide;

        // Caută și procesează toate părțile separate prin '&' din partea dreaptă a producției
        while ((pos = rightSide.find("&")) != string::npos) {

            // Extrage subșirul până la '&' și îl adaugă în vectorul de părți
            rightParts.push_back(rightSide.substr(0, pos));

            // Elimină partea procesată și separatorul '&' din șirul original
            rightSide.erase(0, pos + 1);
        }

        // Verifică dacă a mai rămas ceva în rightSide după procesarea tuturor '&'
        // Acest caz apare pentru ultima parte care nu are un '&' după ea
        if (!rightSide.empty()) {
            // Adaugă ultima parte rămasă în vectorul de părți
            rightParts.push_back(rightSide);
        }

        // Verifică dacă s-au găsit părți valide pentru a crea o producție pentru a fi adaugata in gramatica
        if (!rightParts.empty()) {
            currentGrammar->productions.push_back({currentLeftSide, rightParts});
        }
        currentRightSide = "";
        BEGIN(IN_GRAMMAR);
    }
}
	YY_BREAK
/* Procesează încheierea definiției gramaticii */
case 54:
YY_RULE_SETUP
#line 423 "grammar.l"
{
    if(currentGrammar  && !currentGrammar->productions.empty()) {
        /* Adaugă linie goală între gramatici, exceptând prima */
        if(!firstGrammar) 
            cout << endl;
        
        /* Afișează informațiile despre gramatică și eliberează memoria */
        printGrammarInfo();
        delete currentGrammar;
        currentGrammar = nullptr;
    }

    /* Resetează starea la procesarea normală */
    insideGrammar = false;
    BEGIN(INITIAL);
}
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 440 "grammar.l"
/* Ignora spatiile multiple */ ;
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 441 "grammar.l"
/* Ignră orice caracter nerecunoscut în orice stare */ 
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 443 "grammar.l"
ECHO;
	YY_BREAK
#line 1729 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IN_GRAMMAR):
case YY_STATE_EOF(IN_AUTOMATON):
case YY_STATE_EOF(IN_NONTERMINALS):
case YY_STATE_EOF(IN_ALPHABET_AUTOMATON):
case YY_STATE_EOF(IN_ALPHABET_GRAMMAR):
case YY_STATE_EOF(IN_STATES):
case YY_STATE_EOF(IN_FINAL_STATES):
case YY_STATE_EOF(IN_PRODUCTION):
case YY_STATE_EOF(IN_TRANSITION):
case YY_STATE_EOF(IN_VARIABLE_DOMAIN):
case YY_STATE_EOF(IN_VARIABLE_LOCAL):
case YY_STATE_EOF(READ_AUTOMATON_NAME):
case YY_STATE_EOF(READ_VARIABLE_NAME):
case YY_STATE_EOF(READ_GRAMMAR_NAME):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 333 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 333 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 332);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 443 "grammar.l"


    /* Verifica daca este sau nu variabila locala a automatului*/
bool isLocalVariable(const string& symbol) {
    if(currentVariable && currentVariable->name == symbol) {
        return true;
    }
    return false;
}

string determineGrammarType(const Grammar& g) {
   // Flaguri pentru fiecare tip de gramatică, pornind cu asumpția că sunt toate adevărate
   bool isGR = true; 
   bool isGDC = true;  
   bool isGIC = true;  
   
   // Parcurgem fiecare producție pentru a verifica restricțiile
   for(const auto& prod : g.productions) {
        const string& leftStr = prod.first;              // Partea stângă a producției
        const vector<string>& rightParts = prod.second;  // Partea dreaptă, împărțită în bucati
       
        // Verificăm întâi cazul special pentru producția vidă (S -> ε)
        // În GDC, doar simbolul de start poate produce ε
        bool isEpsilonRule = (rightParts.size() == 1 && rightParts[0] == "e");
        if(isEpsilonRule) {
            if(leftStr != g.startSymbol) {
               isGDC = false;  // Dacă alt simbol produce ε, nu e GDC
            }
            continue;  // Trecem la următoarea producție
        }

        // Verificări pentru Gramatică Regulată (GR)
        // Prima condiție: partea stângă trebuie să fie un singur neterminal si la GIC la fel
        if(g.nonterminals.find(leftStr) == g.nonterminals.end()) {
           isGR = false;
           isGIC = false;
        }

        // Pentru producțiile non-epsilon, verificăm formatul specific GR
        if(!isEpsilonRule) {
            if(rightParts.size() == 1) {
                // Cazul 1 pentru GR: A -> a (un singur terminal)
                if(g.alphabet.find(rightParts[0]) == g.alphabet.end()) {
                   isGR = false;
                }
            } else if(rightParts.size() == 2) {
                // Cazul 2 pentru GR: A -> aB (terminal urmat de neterminal)
                bool firstIsTerminal = g.alphabet.find(rightParts[0]) != g.alphabet.end();
                bool secondIsNonTerminal = g.nonterminals.find(rightParts[1]) != g.nonterminals.end();
                if(!firstIsTerminal || !secondIsNonTerminal) {
                   isGR = false;
                }
            } else {
                isGR = false;  // Mai mult de 2 simboluri
            }
        }

       // Verificare pentru GDC: |α| ≤ |β| (lungimea părții stângi ≤ lungimea părții drepte)
       // Mai întâi separăm partea stângă în tokeni individuali
       vector<string> leftTokens;
       size_t pos = 0;
       string temp = leftStr;
       while ((pos = temp.find("&")) != string::npos) {
           leftTokens.push_back(temp.substr(0, pos));
           temp.erase(0, pos + 1);
       }
       if (!temp.empty()) {
           leftTokens.push_back(temp);
       }

       // Verificăm condiția de lungime pentru GDC
       if(leftTokens.size() > rightParts.size() && !isEpsilonRule) {
           isGDC = false;
       }
   }

   // Returnăm tipul cel mai restrictiv care se potrivește
   if(isGR) return "GR";
   if(isGIC) return "GIC";          
   if(isGDC) return "GDC";                 
   return "GFR";                   
}

void printGrammarInfo() {
    if(!currentGrammar  || currentGrammar->productions.empty()) 
        return;

    cout << "Numele gramaticii: " << currentGrammar->name << endl;
    cout << "Tipul gramaticii: " << determineGrammarType(*currentGrammar) << endl;
    cout << "Numarul de reguli de productie: " << currentGrammar->productions.size() << endl;
    cout << "Alfabetul gramaticii: {";
    bool first = true;
    for(const auto& symbol : currentGrammar->alphabet) {
        if(!first) cout << ", ";
        cout << symbol;
        first = false;
    }
    cout << "}" << endl<<endl;

    firstGrammar = false;
}

bool isDeterministic(const FiniteAutomaton& fa) {
    /* Mapam fiecare pereche (stare, simbol) la mulțimea starilor destinatie
     * Pentru ca automatul sa fie determinist:
     * 1. Nu trebuie să existe tranziții epsilon
     * 2. Pentru fiecare pereche (stare, simbol), trebuie sa existe exact o stare destinatie */
    
    map<pair<string, string>, set<string>> transitionMap;
    
    // Construim un map de tranziții
    for(const auto& t : fa.transitions) {
        transitionMap[{t.fromState, t.symbol}].insert(t.toState);
    }
    
    // Verificăm dacă există tranziții nedeterministe
    for(const auto& transition : transitionMap) {
        if(transition.second.size() > 1 || (transition.first.second == "e")) {
            return false;
        }
    }
    
    return true;
}

void printAutomatonInfo() {
    if(!currentAutomaton) return;
    
    cout << "Numele automatului: " << currentAutomaton->name << endl;
    cout << "Tipul automatului: " << (isDeterministic(*currentAutomaton) ? "Automat finit determinist" : "Automat finit nedeterminist") << endl;
    
    // Filtrăm doar epsilon din alfabet
    set<string> printAlphabet = currentAutomaton->alphabet;
    printAlphabet.erase("e");

    cout << "Alfabetul de intrare: {";
    bool first = true;
    for(const auto& symbol : printAlphabet) {
        if(!first) cout << ", ";
        cout << symbol;
        first = false;
    }
    cout << "}" << endl;
    
    cout << "Numarul de stari: " << currentAutomaton->states.size() << endl;
    cout << "Starea initiala: " << currentAutomaton->initialState << endl;
    
    cout << "Starile finale: {";
    first = true;
    for(const auto& state : currentAutomaton->finalStates) {
        if(!first) cout << ", ";
        cout << state;
        first = false;
    }
    cout << "}" << endl;
    
    cout << "Functia de tranzitie:" << endl;
    for(const auto& t : currentAutomaton->transitions) {
        cout << "m(" << t.fromState << ", " << t.symbol << ") = " << t.toState << endl;
    }
    cout << endl;

    // Printam variabila locala gasita daca apartine automatului actual
    if(currentVariable && currentVariable->isLocal && insideAutomaton) {
        cout << "Variabila locala:" << endl;
        cout << "    Identificator: " << currentVariable->name << endl;
        cout << "    Domeniu: {";
        first = true;
        for(const auto& elem : currentVariable->domain) {
            if(!first) cout << ", ";
            cout << elem;
            first = false;
        }
        cout << "}" << endl << endl;
    }
}

int main(int argc, char* argv[]) {
    if(argc != 2) {
        return 1;
    }
    
    FILE* file = fopen(argv[1], "r");
    if(!file) {
        return 1;
    }
    
    yyin = file;
    yylex();
    
    fclose(file);
    return 0;
}
